version: "3"
services:
  database:
    image: mysql/mysql-server:5.7
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=demo_java
      - MYSQL_PASSWORD=1234
      - MYSQL_DATABASE=database
    ports:
      - 3306:3306

  credit:
    image: springboot/springboot-credit
    build: .\credit
    ports:
      - 8080:8080
    depends_on:
      - database
      - customer
      - product
    environment:
      - DATASOURCE_URL=jdbc:mysql://database:3306/task?useSSL=falsek&user=root&password=myroot&autoReconnect=true

  customer:
    image: springboot/springboot-customer
    network_mode: bridge
    build: .\customer
    ports:
      - 8081:8081
    depends_on:
      - database
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=hello_java
      - DATABASE_USER=demo_java
      - DATABASE_PASSWORD=1234

  product:
    image: springboot/springboot-product
    build: .\product
    ports:
      - 8082:8082
    depends_on:
      - database