version: "3"
services:
  database:
    image: mysql/mysql-server:5.7
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=demo_java
      - MYSQL_PASSWORD=1234
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    ports:
      - 3306:3306

  credit:
    image: springboot/springboot-credit
    build: .\credit
    container_name: credit
    ports:
      - 8080:8080
    depends_on:
      - database
      - customer
      - product
    command: /bin/bash -c "sleep 30;"

  customer:
    image: springboot/springboot-customer
    build: .\customer
    container_name: customer
    ports:
      - 8081:8081
    depends_on:
      - database
    command: /bin/bash -c "sleep 30;"

  product:
    image: springboot/springboot-product
    build: .\product
    container_name: product
    ports:
      - 8082:8082
    depends_on:
      - database
    command: /bin/bash -c "sleep 30;"