version: "3"
services:
  database:
    image: mysql:latest
    container_name: database
    volumes:
      - ./database/database.sql:/docker-entrypoint-initdb.d/database.sql
    environment:
      - MYSQL_ROOT_PASSWORD=myroot
      - MYSQL_DATABASE=task
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "task" ,"ping", "-h", "database"]
      timeout: 1s
      retries: 100
    networks:
      - dataCredt

  credit:
    image: springboot/springboot-credit
    build: .\credit
    ports:
      - 8080:8080
    depends_on:
      - database
      #- customer
      #- product
    environment:
      - DATASOURCE_URL=jdbc:mysql://database:3306/task?useSSL=falsek&user=root&password=myroot&autoReconnect=true
    networks:
      - dataCredt

  #ustomer:
  #  image: springboot/springboot-customer
  #  build: .\customer
  #  ports:
  #    - 8081:8081
  #  depends_on:
  #    - database

  #product:
  #  image: springboot/springboot-product
  #  build: .\product
  #  ports:
  #    - 8082:8082
  #  depends_on:
  #    - database

networks:
  dataCredt: